name: textmining-labs
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.5.2
  - nb_conda=2.2.1
  - scikit-learn=1.1.1
  - pandas=1.4.4
  - pip=22.1.2
  - seaborn=0.11.2
  - gensim=4.2.0
  - spacy[transformers]=3.3.1
  - spacy-transformers=1.1.5
  - wordcloud=1.8.2.2
  - tornado=6.2
  - jedi=0.18.1
  - pip:
    - pyLDAvis==3.3.1
